name: Deploy to Raspberry Pi

on:
  workflow_run:
    workflows: ["CI/CD Pipeline"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Add Raspberry Pi to known_hosts
      run: |
        ssh-keyscan -H 192.168.50.122 >> ~/.ssh/known_hosts

    - name: Setup SSH agent
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Pull Docker image and run container on Raspberry Pi
      run: |
        ssh tandc181123@192.168.50.122 << EOF
          docker pull tandc181123/demo:latest
          docker stop demo || true
          docker rm demo || true
          docker run -d --name demo -p 8080:8080 tandc181123/demo:latest
        EOF

